version: 0.2
env:
  secrets-manager:
    githubtoken: codebuild-user:token
phases:
  install:
    runtime-versions:
      nodejs: 10  
  build:
    commands:
      - ./run_tests.sh

reports:
  redirect-tests-results:
    files:
      - tests-results/*
